name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: "stable"

      - name: Install dependencies
        run: |
          flutter pub get
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config libgtk-3-dev

      - name: Build Linux app
        run: flutter build linux --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/

  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: "stable"

      - name: Install dependencies
        run: |
          flutter pub get
          sudo apt-get update
          sudo apt-get install -y wget fuse cmake ninja-build pkg-config libgtk-3-dev

      - name: Build Linux app
        run: flutter build linux --release

      - name: Build AppImage
        run: |
          ./scripts/build-appimage.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-format-folder-appimage
          path: auto-format-folder-x86_64.AppImage

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: auto-format-folder-x86_64.AppImage
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
