name: CI/CD Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: "stable"

      - name: Install dependencies
        run: |
          flutter pub get
          sudo apt-get update
          sudo apt-get install -y wget fuse cmake ninja-build pkg-config libgtk-3-dev

      - name: Build Linux app
        run: flutter build linux --release

      - name: Upload Linux build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/

      - name: Build AppImage
        run: |
          ./scripts/build-appimage.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-format-folder-appimage
          path: auto-format-folder-x86_64.AppImage

      - name: Release drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
      - name: Upload AppImage to Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{steps.release_drafter.outputs.upload_url}}
          asset_path: auto-format-folder-x86_64.AppImage
          asset_name: auto-format-folder-x86_64.AppImage
